### ISSUE TITLE
Option to suppress all prints

### ISSUE THREAD

**Issue by Moritzheine** [ishikota/PyPokerEngine#73]
The constant stream of prints when running the poker game makes it very hard to track my own prints. A  flag for the "setup_config" function would be nice, like
`config = setup_config(max_round=10, initial_stack=100, small_blind_amount=5, show_game_messages=False)
`

**Comment by schreven** [comment]
This option exists, it is 'verbose'. Just do:
`config = setup_config(max_round=10, initial_stack=100, small_blind_amount=5, verbose=0)`
Please close your issue if this is what you were looking for.

**Comment by Moritzheine** [comment]
'verbose' is not a valid argument for 'setup_config':
`TypeError: setup_config() got an unexpected keyword argument 'verbose'`

**Comment by Moritzheine** [comment]
You were right though, but for the 'start_poker' function. Thank you

`game_result = start_poker(config, verbose=0)
`

**Comment by schreven** [comment]
Good to hear. Sorry about the error
